export const projectData = [
    {
        id: 1,
        name: "Youtube clone",
        url: "https://polite-manatee-5e864a.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
    {
        id: 2,
        name: "Learning hub",
        url: "https://sage-crisp-5fecd3.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
    {
        id: 3,
        name: "random zip",
        url: "https://lustrous-kangaroo-4a8a65.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
    {
        id: 4,
        name: "top courses",
        url: "https://glistening-rolypoly-8b5745.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
    {
        id: 5,
        name: "weather app",
        url: "https://lucky-llama-6a15d4.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
    {
        id: 6,
        name: "shoping cart",
        url: "https://grand-otter-5d6111.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
    {
        id: 7,
        name: "study notion demo",
        url: "https://strong-gecko-d64ee7.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
    {
        id: 8,
        name: "testimonial app",
        url: "https://jade-mandazi-114a9e.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
    {
        id: 9,
        name: "world classic fashion",
        url: "https://roaring-rabanadas-402af0.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
    {
        id: 10,
        name: "random password genrator",
        url: "https://clinquant-treacle-d326f8.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
    {
        id: 11,
        name: "razzerpay clone",
        url: "https://animated-lamington-ab712a.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
    {
        id: 12,
        name: "redmi mi clone",
        url: "https://incandescent-sunburst-0cf480.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
    {
        id: 13,
        name: "counter react app",
        url: "https://cheerful-bavarois-949669.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
    {
        id: 14,
        name: "tik tak app",
        url: "https://quiet-blini-66befd.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
    {
        id: 15,
        name: "tour app react",
        url: "https://enchanting-jalebi-e6acdd.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
    {
        id: 16,
        name: "react form",
        url: "https://snazzy-cucurucho-9bd7af.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
    {
        id: 17,
        name: "Discord clone",
        url: "https://snazzy-khapse-820d89.netlify.app",
        description: "sssss",
        image: "ddddd",
    },
];
