export const projectData = [
    {
        id: 1,
        name: "Youtube clone",
        url: "https://polite-manatee-5e864a.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662580/portfolio-image/youtube-clone_rdcxkw.png",
    },
    {
        id: 2,
        name: "Learning hub",
        url: "https://sage-crisp-5fecd3.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662578/portfolio-image/learning-hub_gsx6u3.png",
    },
    {
        id: 3,
        name: "random zip",
        url: "https://lustrous-kangaroo-4a8a65.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662577/portfolio-image/random-zip-react-app_extwkf.png",
    },
    {
        id: 4,
        name: "top courses",
        url: "https://glistening-rolypoly-8b5745.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662575/portfolio-image/top-courses-react-app_vcrdxi.png",
    },
    {
        id: 5,
        name: "weather app",
        url: "https://lucky-llama-6a15d4.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662580/portfolio-image/wether-app_fseux5.png",
    },
    {
        id: 6,
        name: "shoping cart",
        url: "https://grand-otter-5d6111.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662576/portfolio-image/shoping-cart-react-app_b4a6eq.png",
    },
    {
        id: 7,
        name: "study notion demo",
        url: "https://strong-gecko-d64ee7.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662578/portfolio-image/study-notion-react-app_gszzgq.png",
    },
    {
        id: 8,
        name: "testimonial app",
        url: "https://jade-mandazi-114a9e.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662574/portfolio-image/testimonial-react-app_xkhjfw.png",
    },
    {
        id: 9,
        name: "world classic fashion",
        url: "https://roaring-rabanadas-402af0.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662583/portfolio-image/world-classic-fashion_quwkf0.png",
    },
    {
        id: 10,
        name: "random password genrator",
        url: "https://clinquant-treacle-d326f8.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662578/portfolio-image/password-genrator_lndimz.png",
    },
    {
        id: 11,
        name: "razzerpay clone",
        url: "https://animated-lamington-ab712a.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662575/portfolio-image/razerpay-clone_jo8olj.png",
    },
    {
        id: 12,
        name: "redmi mi clone",
        url: "https://incandescent-sunburst-0cf480.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662580/portfolio-image/redmi-clone_nxsyua.png",
    },
    {
        id: 13,
        name: "counter react app",
        url: "https://cheerful-bavarois-949669.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662574/portfolio-image/counter-react-app_go6kki.png",
    },
    {
        id: 14,
        name: "tik tak app",
        url: "https://quiet-blini-66befd.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662575/portfolio-image/tik-tak-app_ahnbks.png",
    },
    {
        id: 15,
        name: "tour app react",
        url: "https://enchanting-jalebi-e6acdd.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662582/portfolio-image/tour-app-react_rvogcf.png",
    },
    {
        id: 16,
        name: "react form",
        url: "https://snazzy-cucurucho-9bd7af.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662574/portfolio-image/form-react-app_amlz40.png",
    },
    {
        id: 17,
        name: "Discord clone",
        url: "https://snazzy-khapse-820d89.netlify.app",
        description: "sssss",
        image: "https://res.cloudinary.com/dsxheywlc/image/upload/v1694662576/portfolio-image/dishcord-clone_jvt1ir.png",
    },
];
